name: Romain Boonen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6776867660228163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ddddd5'
    - '#0d182a'
    - '#516775'
    - '#7d8e98'
    - '#27400f'
  brandStrength: 0.6875
  lightness: 0.7161595840007067
  saturation: 0
  rhythmicContrast: 0
purpose: []
